 

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PersonalityMode = IDL.Variant({
  'pro_coder' : IDL.Null,
  'strict_teacher' : IDL.Null,
  'friendly' : IDL.Null,
});
export const Message = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const ChatSessionDTO = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'messages' : IDL.Vec(Message),
  'createdAt' : IDL.Int,
});
export const Flashcard = IDL.Record({
  'id' : IDL.Text,
  'front' : IDL.Text,
  'interval' : IDL.Int,
  'back' : IDL.Text,
  'difficulty' : IDL.Int,
  'nextReview' : IDL.Int,
  'easeFactor' : IDL.Float64,
});
export const FlashcardDeckDTO = IDL.Record({
  'id' : IDL.Text,
  'subject' : IDL.Text,
  'cards' : IDL.Vec(Flashcard),
  'name' : IDL.Text,
});
export const Goal = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'isCompleted' : IDL.Bool,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'targetDate' : IDL.Int,
});
export const Note = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'topic' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
});
export const Profile = IDL.Record({
  'preferredLanguage' : IDL.Text,
  'displayName' : IDL.Text,
  'createdAt' : IDL.Int,
  'personalityMode' : PersonalityMode,
});
export const ProgressStat = IDL.Record({
  'subject' : IDL.Text,
  'lastUpdated' : IDL.Int,
  'masteryPercent' : IDL.Float64,
});
export const QuizResult = IDL.Record({
  'id' : IDL.Text,
  'subject' : IDL.Text,
  'score' : IDL.Int,
  'totalQuestions' : IDL.Int,
  'timestamp' : IDL.Int,
});
export const StudyStreak = IDL.Record({
  'lastStudyDate' : IDL.Int,
  'currentStreak' : IDL.Int,
});

export const idlService = IDL.Service({
  'addCard' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'addMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'completeGoal' : IDL.Func([IDL.Text], [], []),
  'createChatSession' : IDL.Func([IDL.Text], [IDL.Text], []),
  'createDeck' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'createGoal' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [IDL.Text], []),
  'createNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'createProfile' : IDL.Func([IDL.Text, PersonalityMode, IDL.Text], [], []),
  'deleteChatSession' : IDL.Func([IDL.Text], [], []),
  'deleteNote' : IDL.Func([IDL.Text], [], []),
  'getChatMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
  'getChatSessions' : IDL.Func([], [IDL.Vec(ChatSessionDTO)], ['query']),
  'getDeckCards' : IDL.Func([IDL.Text], [IDL.Vec(Flashcard)], ['query']),
  'getDecks' : IDL.Func([], [IDL.Vec(FlashcardDeckDTO)], ['query']),
  'getGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
  'getNote' : IDL.Func([IDL.Text], [Note], ['query']),
  'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getProfile' : IDL.Func([], [Profile], ['query']),
  'getProgressStats' : IDL.Func([], [IDL.Vec(ProgressStat)], ['query']),
  'getQuizResults' : IDL.Func([], [IDL.Vec(QuizResult)], ['query']),
  'getStudyStreak' : IDL.Func([], [StudyStreak], ['query']),
  'recordQuizResult' : IDL.Func([IDL.Text, IDL.Int, IDL.Int], [IDL.Text], []),
  'recordStudyActivity' : IDL.Func([], [], []),
  'updateCardReview' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int, IDL.Float64],
      [],
      [],
    ),
  'updateNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateProfile' : IDL.Func([IDL.Text, PersonalityMode, IDL.Text], [], []),
  'updateProgressStat' : IDL.Func([IDL.Text, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PersonalityMode = IDL.Variant({
    'pro_coder' : IDL.Null,
    'strict_teacher' : IDL.Null,
    'friendly' : IDL.Null,
  });
  const Message = IDL.Record({
    'content' : IDL.Text,
    'role' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const ChatSessionDTO = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'messages' : IDL.Vec(Message),
    'createdAt' : IDL.Int,
  });
  const Flashcard = IDL.Record({
    'id' : IDL.Text,
    'front' : IDL.Text,
    'interval' : IDL.Int,
    'back' : IDL.Text,
    'difficulty' : IDL.Int,
    'nextReview' : IDL.Int,
    'easeFactor' : IDL.Float64,
  });
  const FlashcardDeckDTO = IDL.Record({
    'id' : IDL.Text,
    'subject' : IDL.Text,
    'cards' : IDL.Vec(Flashcard),
    'name' : IDL.Text,
  });
  const Goal = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'isCompleted' : IDL.Bool,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'targetDate' : IDL.Int,
  });
  const Note = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'topic' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
  });
  const Profile = IDL.Record({
    'preferredLanguage' : IDL.Text,
    'displayName' : IDL.Text,
    'createdAt' : IDL.Int,
    'personalityMode' : PersonalityMode,
  });
  const ProgressStat = IDL.Record({
    'subject' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'masteryPercent' : IDL.Float64,
  });
  const QuizResult = IDL.Record({
    'id' : IDL.Text,
    'subject' : IDL.Text,
    'score' : IDL.Int,
    'totalQuestions' : IDL.Int,
    'timestamp' : IDL.Int,
  });
  const StudyStreak = IDL.Record({
    'lastStudyDate' : IDL.Int,
    'currentStreak' : IDL.Int,
  });
  
  return IDL.Service({
    'addCard' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'addMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'completeGoal' : IDL.Func([IDL.Text], [], []),
    'createChatSession' : IDL.Func([IDL.Text], [IDL.Text], []),
    'createDeck' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'createGoal' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [IDL.Text], []),
    'createNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'createProfile' : IDL.Func([IDL.Text, PersonalityMode, IDL.Text], [], []),
    'deleteChatSession' : IDL.Func([IDL.Text], [], []),
    'deleteNote' : IDL.Func([IDL.Text], [], []),
    'getChatMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
    'getChatSessions' : IDL.Func([], [IDL.Vec(ChatSessionDTO)], ['query']),
    'getDeckCards' : IDL.Func([IDL.Text], [IDL.Vec(Flashcard)], ['query']),
    'getDecks' : IDL.Func([], [IDL.Vec(FlashcardDeckDTO)], ['query']),
    'getGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
    'getNote' : IDL.Func([IDL.Text], [Note], ['query']),
    'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getProfile' : IDL.Func([], [Profile], ['query']),
    'getProgressStats' : IDL.Func([], [IDL.Vec(ProgressStat)], ['query']),
    'getQuizResults' : IDL.Func([], [IDL.Vec(QuizResult)], ['query']),
    'getStudyStreak' : IDL.Func([], [StudyStreak], ['query']),
    'recordQuizResult' : IDL.Func([IDL.Text, IDL.Int, IDL.Int], [IDL.Text], []),
    'recordStudyActivity' : IDL.Func([], [], []),
    'updateCardReview' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int, IDL.Float64],
        [],
        [],
      ),
    'updateNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateProfile' : IDL.Func([IDL.Text, PersonalityMode, IDL.Text], [], []),
    'updateProgressStat' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };