 

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatSessionDTO {
  'id' : string,
  'title' : string,
  'messages' : Array<Message>,
  'createdAt' : bigint,
}
export interface Flashcard {
  'id' : string,
  'front' : string,
  'interval' : bigint,
  'back' : string,
  'difficulty' : bigint,
  'nextReview' : bigint,
  'easeFactor' : number,
}
export interface FlashcardDeckDTO {
  'id' : string,
  'subject' : string,
  'cards' : Array<Flashcard>,
  'name' : string,
}
export interface Goal {
  'id' : string,
  'title' : string,
  'isCompleted' : boolean,
  'createdAt' : bigint,
  'description' : string,
  'targetDate' : bigint,
}
export interface Message {
  'content' : string,
  'role' : string,
  'timestamp' : bigint,
}
export interface Note {
  'id' : string,
  'title' : string,
  'topic' : string,
  'content' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
}
export type PersonalityMode = { 'pro_coder' : null } |
  { 'strict_teacher' : null } |
  { 'friendly' : null };
export interface Profile {
  'preferredLanguage' : string,
  'displayName' : string,
  'createdAt' : bigint,
  'personalityMode' : PersonalityMode,
}
export interface ProgressStat {
  'subject' : string,
  'lastUpdated' : bigint,
  'masteryPercent' : number,
}
export interface QuizResult {
  'id' : string,
  'subject' : string,
  'score' : bigint,
  'totalQuestions' : bigint,
  'timestamp' : bigint,
}
export interface StudyStreak {
  'lastStudyDate' : bigint,
  'currentStreak' : bigint,
}
export interface _SERVICE {
  'addCard' : ActorMethod<[string, string, string], string>,
  'addMessage' : ActorMethod<[string, string, string], undefined>,
  'completeGoal' : ActorMethod<[string], undefined>,
  'createChatSession' : ActorMethod<[string], string>,
  'createDeck' : ActorMethod<[string, string], string>,
  'createGoal' : ActorMethod<[string, string, bigint], string>,
  'createNote' : ActorMethod<[string, string, string], string>,
  'createProfile' : ActorMethod<[string, PersonalityMode, string], undefined>,
  'deleteChatSession' : ActorMethod<[string], undefined>,
  'deleteNote' : ActorMethod<[string], undefined>,
  'getChatMessages' : ActorMethod<[string], Array<Message>>,
  'getChatSessions' : ActorMethod<[], Array<ChatSessionDTO>>,
  'getDeckCards' : ActorMethod<[string], Array<Flashcard>>,
  'getDecks' : ActorMethod<[], Array<FlashcardDeckDTO>>,
  'getGoals' : ActorMethod<[], Array<Goal>>,
  'getNote' : ActorMethod<[string], Note>,
  'getNotes' : ActorMethod<[], Array<Note>>,
  'getProfile' : ActorMethod<[], Profile>,
  'getProgressStats' : ActorMethod<[], Array<ProgressStat>>,
  'getQuizResults' : ActorMethod<[], Array<QuizResult>>,
  'getStudyStreak' : ActorMethod<[], StudyStreak>,
  'recordQuizResult' : ActorMethod<[string, bigint, bigint], string>,
  'recordStudyActivity' : ActorMethod<[], undefined>,
  'updateCardReview' : ActorMethod<[string, string, bigint, number], undefined>,
  'updateNote' : ActorMethod<[string, string, string, string], undefined>,
  'updateProfile' : ActorMethod<[string, PersonalityMode, string], undefined>,
  'updateProgressStat' : ActorMethod<[string, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];