/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Goal {
    id: string;
    title: string;
    isCompleted: boolean;
    createdAt: bigint;
    description: string;
    targetDate: bigint;
}
export interface ChatSessionDTO {
    id: string;
    title: string;
    messages: Array<Message>;
    createdAt: bigint;
}
export interface Flashcard {
    id: string;
    front: string;
    interval: bigint;
    back: string;
    difficulty: bigint;
    nextReview: bigint;
    easeFactor: number;
}
export interface ProgressStat {
    subject: string;
    lastUpdated: bigint;
    masteryPercent: number;
}
export interface Message {
    content: string;
    role: string;
    timestamp: bigint;
}
export interface QuizResult {
    id: string;
    subject: string;
    score: bigint;
    totalQuestions: bigint;
    timestamp: bigint;
}
export interface StudyStreak {
    lastStudyDate: bigint;
    currentStreak: bigint;
}
export interface Profile {
    preferredLanguage: string;
    displayName: string;
    createdAt: bigint;
    personalityMode: PersonalityMode;
}
export interface FlashcardDeckDTO {
    id: string;
    subject: string;
    cards: Array<Flashcard>;
    name: string;
}
export interface Note {
    id: string;
    title: string;
    topic: string;
    content: string;
    createdAt: bigint;
    updatedAt: bigint;
}
export enum PersonalityMode {
    pro_coder = "pro_coder",
    strict_teacher = "strict_teacher",
    friendly = "friendly"
}
export interface backendInterface {
    addCard(deckId: string, front: string, back: string): Promise<string>;
    addMessage(sessionId: string, role: string, content: string): Promise<void>;
    completeGoal(goalId: string): Promise<void>;
    createChatSession(title: string): Promise<string>;
    createDeck(name: string, subject: string): Promise<string>;
    createGoal(title: string, description: string, targetDate: bigint): Promise<string>;
    createNote(title: string, content: string, topic: string): Promise<string>;
    createProfile(displayName: string, mode: PersonalityMode, language: string): Promise<void>;
    deleteChatSession(sessionId: string): Promise<void>;
    deleteNote(noteId: string): Promise<void>;
    getChatMessages(sessionId: string): Promise<Array<Message>>;
    getChatSessions(): Promise<Array<ChatSessionDTO>>;
    getDeckCards(deckId: string): Promise<Array<Flashcard>>;
    getDecks(): Promise<Array<FlashcardDeckDTO>>;
    getGoals(): Promise<Array<Goal>>;
    getNote(noteId: string): Promise<Note>;
    getNotes(): Promise<Array<Note>>;
    getProfile(): Promise<Profile>;
    getProgressStats(): Promise<Array<ProgressStat>>;
    getQuizResults(): Promise<Array<QuizResult>>;
    getStudyStreak(): Promise<StudyStreak>;
    recordQuizResult(subject: string, score: bigint, totalQuestions: bigint): Promise<string>;
    recordStudyActivity(): Promise<void>;
    updateCardReview(deckId: string, cardId: string, interval: bigint, easeFactor: number): Promise<void>;
    updateNote(noteId: string, title: string, content: string, topic: string): Promise<void>;
    updateProfile(displayName: string, mode: PersonalityMode, language: string): Promise<void>;
    updateProgressStat(subject: string, masteryPercent: number): Promise<void>;
}
import type { PersonalityMode as _PersonalityMode, Profile as _Profile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCard(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addCard(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCard(arg0, arg1, arg2);
            return result;
        }
    }
    async addMessage(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async completeGoal(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeGoal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeGoal(arg0);
            return result;
        }
    }
    async createChatSession(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createChatSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChatSession(arg0);
            return result;
        }
    }
    async createDeck(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createDeck(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDeck(arg0, arg1);
            return result;
        }
    }
    async createGoal(arg0: string, arg1: string, arg2: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createGoal(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGoal(arg0, arg1, arg2);
            return result;
        }
    }
    async createNote(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createNote(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNote(arg0, arg1, arg2);
            return result;
        }
    }
    async createProfile(arg0: string, arg1: PersonalityMode, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createProfile(arg0, to_candid_PersonalityMode_n1(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProfile(arg0, to_candid_PersonalityMode_n1(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async deleteChatSession(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChatSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChatSession(arg0);
            return result;
        }
    }
    async deleteNote(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNote(arg0);
            return result;
        }
    }
    async getChatMessages(arg0: string): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatMessages(arg0);
            return result;
        }
    }
    async getChatSessions(): Promise<Array<ChatSessionDTO>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatSessions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatSessions();
            return result;
        }
    }
    async getDeckCards(arg0: string): Promise<Array<Flashcard>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeckCards(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeckCards(arg0);
            return result;
        }
    }
    async getDecks(): Promise<Array<FlashcardDeckDTO>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDecks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDecks();
            return result;
        }
    }
    async getGoals(): Promise<Array<Goal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGoals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGoals();
            return result;
        }
    }
    async getNote(arg0: string): Promise<Note> {
        if (this.processError) {
            try {
                const result = await this.actor.getNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNote(arg0);
            return result;
        }
    }
    async getNotes(): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotes();
            return result;
        }
    }
    async getProfile(): Promise<Profile> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_Profile_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_Profile_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProgressStats(): Promise<Array<ProgressStat>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgressStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgressStats();
            return result;
        }
    }
    async getQuizResults(): Promise<Array<QuizResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizResults();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizResults();
            return result;
        }
    }
    async getStudyStreak(): Promise<StudyStreak> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudyStreak();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudyStreak();
            return result;
        }
    }
    async recordQuizResult(arg0: string, arg1: bigint, arg2: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.recordQuizResult(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordQuizResult(arg0, arg1, arg2);
            return result;
        }
    }
    async recordStudyActivity(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordStudyActivity();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordStudyActivity();
            return result;
        }
    }
    async updateCardReview(arg0: string, arg1: string, arg2: bigint, arg3: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCardReview(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCardReview(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateNote(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNote(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNote(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateProfile(arg0: string, arg1: PersonalityMode, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, to_candid_PersonalityMode_n1(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, to_candid_PersonalityMode_n1(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async updateProgressStat(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProgressStat(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProgressStat(arg0, arg1);
            return result;
        }
    }
}
function from_candid_PersonalityMode_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PersonalityMode): PersonalityMode {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Profile_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile): Profile {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    preferredLanguage: string;
    displayName: string;
    createdAt: bigint;
    personalityMode: _PersonalityMode;
}): {
    preferredLanguage: string;
    displayName: string;
    createdAt: bigint;
    personalityMode: PersonalityMode;
} {
    return {
        preferredLanguage: value.preferredLanguage,
        displayName: value.displayName,
        createdAt: value.createdAt,
        personalityMode: from_candid_PersonalityMode_n5(_uploadFile, _downloadFile, value.personalityMode)
    };
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pro_coder: null;
} | {
    strict_teacher: null;
} | {
    friendly: null;
}): PersonalityMode {
    return "pro_coder" in value ? PersonalityMode.pro_coder : "strict_teacher" in value ? PersonalityMode.strict_teacher : "friendly" in value ? PersonalityMode.friendly : value;
}
function to_candid_PersonalityMode_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PersonalityMode): _PersonalityMode {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PersonalityMode): {
    pro_coder: null;
} | {
    strict_teacher: null;
} | {
    friendly: null;
} {
    return value == PersonalityMode.pro_coder ? {
        pro_coder: null
    } : value == PersonalityMode.strict_teacher ? {
        strict_teacher: null
    } : value == PersonalityMode.friendly ? {
        friendly: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
